import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'
import { CENTER_ROLE } from '@/constants/role.constant'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'ظ„ظˆط­ط© ط§ظ„طھط­ظƒظ…',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'centers',
        path: '/centers',
        title: 'ط؛ط±ظپظٹ',
        translateKey: 'nav.singleMenuItem',
        icon: 'store',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'createCenter',
        path: '/create-center',
        title: 'ط¥ظ†ط´ط§ط، ط­ط¬ط±ط©',
        translateKey: 'nav.singleMenuItem',
        icon: 'groupMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'members',
        path: '/members',
        title: 'ط§ظ„ط¹ظ…ظ„ط§ط،',
        translateKey: 'nav.singleMenuItem',
        icon: 'account',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'bookings',
        path: '/bookings',
        title: 'ط¥ط¯ط§ط±ط© ط§ظ„ط­ط¬ظˆط²ط§طھ',
        translateKey: 'nav.singleMenuItem',
        icon: 'groupMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'chat',
        path: '/chat',
        title: 'المحادثات',
        translateKey: 'nav.singleMenuItem',
        icon: 'groupMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },

    // {
    //     key: 'singleMenuItem',
    //     path: '/single-menu-view',
    //     title: 'ط¢غŒطھظ… ظ…ظ†ظˆغŒ طھع©غŒ',
    //     translateKey: 'nav.singleMenuItem',
    //     icon: 'singleMenu',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    // {
    //     key: 'collapseMenu',
    //     path: '',
    //     title: 'ظ…ظ†ظˆغŒ ط¨ط§ط²ط´ظˆظ†ط¯ظ‡',
    //     translateKey: 'nav.collapseMenu.collapseMenu',
    //     icon: 'collapseMenu',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'collapseMenu.item1',
    //             path: '/collapse-menu-item-view-1',
    //             title: 'ط¢غŒطھظ… ط§ظˆظ„ ظ…ظ†ظˆغŒ ط¨ط§ط²ط´ظˆظ†ط¯ظ‡',
    //             translateKey: 'nav.collapseMenu.item1',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'collapseMenu.item2',
    //             path: '/collapse-menu-item-view-2',
    //             title: 'ط¢غŒطھظ… ط¯ظˆظ… ظ…ظ†ظˆغŒ ط¨ط§ط²ط´ظˆظ†ط¯ظ‡',
    //             translateKey: 'nav.collapseMenu.item2',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },
    // {
    //     key: 'groupMenu',
    //     path: '',
    //     title: 'ظ…ظ†ظˆغŒ ع¯ط±ظˆظ‡غŒ',
    //     translateKey: 'nav.groupMenu.groupMenu',
    //     icon: 'groupMenu',
    //     type: NAV_ITEM_TYPE_TITLE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'groupMenu.single',
    //             path: '/group-single-menu-item-view',
    //             title: 'ط¢غŒطھظ… طھع©غŒ ظ…ظ†ظˆغŒ ع¯ط±ظˆظ‡غŒ',
    //             translateKey: 'nav.groupMenu.single',
    //             icon: 'groupSingleMenu',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'groupMenu.collapse',
    //             path: '',
    //             title: 'ظ…ظ†ظˆغŒ ط¨ط§ط²ط´ظˆظ†ط¯ظ‡ ع¯ط±ظˆظ‡غŒ',
    //             translateKey: 'nav.groupMenu.collapse.collapse',
    //             icon: 'groupCollapseMenu',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [],
    //             subMenu: [
    //                 {
    //                     key: 'groupMenu.collapse.item1',
    //                     path: '/group-collapse-menu-item-view-1',
    //                     title: 'ط¢غŒطھظ… ط§ظˆظ„ ظ…ظ†ظˆغŒ ط¨ط§ط²ط´ظˆظ†ط¯ظ‡',
    //                     translateKey: 'nav.groupMenu.collapse.item1',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'groupMenu.collapse.item2',
    //                     path: '/group-collapse-menu-item-view-2',
    //                     title: 'ط¢غŒطھظ… ط¯ظˆظ… ظ…ظ†ظˆغŒ ط¨ط§ط²ط´ظˆظ†ط¯ظ‡',
    //                     translateKey: 'nav.groupMenu.collapse.item2',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [],
    //                     subMenu: [],
    //                 },
    //             ],
    //         },
    //     ],
    // },
]

export default navigationConfig

