import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'لوحة التحكم',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'centers',
        path: '',
        title: 'مراكزي',
        translateKey: 'nav.singleMenuItem',
        icon: 'fileManager',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'centers',
                path: '/centers',
                title: 'کل الحجر',
                translateKey: 'nav.singleMenuItem',
                icon: 'store',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'newCenter',
                path: '/new-center',
                title: 'مرکز جدید',
                translateKey: 'nav.singleMenuItem',
                icon: 'groupMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    // {
    //     key: 'centers',
    //     path: '/centers',
    //     title: 'مراكزي',
    //     translateKey: 'nav.singleMenuItem',
    //     icon: 'store',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    // {
    //     key: 'createCenter',
    //     path: '/create-center',
    //     title: 'إنشاء مركز',
    //     translateKey: 'nav.singleMenuItem',
    //     icon: 'groupMenu',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    {
        key: 'members',
        path: '/members',
        title: 'العملاء',
        translateKey: 'nav.singleMenuItem',
        icon: 'account',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'bookings',
        path: '/bookings',
        title: 'إدارة الحجوزات',
        translateKey: 'nav.singleMenuItem',
        icon: 'groupMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'chat',
        path: '/chat',
        title: 'المحادثات',
        translateKey: 'nav.singleMenuItem',
        icon: 'groupMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'workCalendar',
        path: '/work-calendar',
        title: 'تقويم العمل',
        translateKey: 'nav.singleMenuItem',
        icon: 'calendarCheck',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'admin.title',
        path: '',
        title: 'Administration',
        translateKey: 'nav.admin.title',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'admin.services',
                path: '/admin/services',
                title: 'Services',
                translateKey: 'nav.admin.services',
                icon: 'fileManager',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                permissions: ['services.view'],
                subMenu: [],
            },
            {
                key: 'admin.agencies',
                path: '/admin/agencies',
                title: 'Agencies',
                translateKey: 'nav.admin.agencies',
                icon: 'store',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                permissions: ['agencies.view'],
                subMenu: [],
            },
            {
                key: 'admin.organizations',
                path: '/admin/organizations',
                title: 'Organizations',
                translateKey: 'nav.admin.organizations',
                icon: 'groupMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                permissions: ['organizations.view'],
                subMenu: [],
            },
            {
                key: 'admin.users',
                path: '/admin/users',
                title: 'Users',
                translateKey: 'nav.admin.users',
                icon: 'account',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                permissions: ['users.view'],
                subMenu: [],
            },
            {
                key: 'admin.roles',
                path: '/admin/roles',
                title: 'Roles',
                translateKey: 'nav.admin.roles',
                icon: 'groupMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                permissions: ['roles.view'],
                subMenu: [],
            },
            {
                key: 'admin.permissions',
                path: '/admin/permissions',
                title: 'Permissions',
                translateKey: 'nav.admin.permissions',
                icon: 'groupMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                permissions: ['permissions.view'],
                subMenu: [],
            },
            {
                key: 'admin.settings',
                path: '/admin/settings/general',
                title: 'Settings',
                translateKey: 'nav.admin.settings',
                icon: 'groupMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                permissions: ['general settings'],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
